### ISSUE TITLE
ImportError: Bio.Alphabet has been removed from Biopython.

### ISSUE THREAD

**Issue by ywe20** [fallerlab/Ribo-ODDR#5]
Hi, I got an error message when using src/Ribo-ODDR.py -h, which seems to be raised because I am now using biopython==1.78, which removed Bio.Alphabet, and I guess it might work if I rolled back to early versions. Do you have any suggestions?

Traceback (most recent call last):
  File "src/Ribo-ODDR.py", line 37, in <module>
    from Bio.Alphabet import generic_dna, generic_rna
  File "/home/ywei/.local/lib/python3.8/site-packages/Bio/Alphabet/__init__.py", line 20, in <module>
    raise ImportError(
ImportError: Bio.Alphabet has been removed from Biopython.

Regards,
Iris

**Comment by ferhatalkan** [comment]
Hi Iris, sorry for this inconvenience. I have been using biopython version 1.76 and wasn't aware that Bio.Alphabet is removed in 1.78. Currently, I can only recommend to roll back to 1.76, but I will think of a solution for the next release. Thanks for reporting the issue.

**Comment by ywe20** [comment]
> Hi Iris, sorry for this inconvenience. I have been using biopython version 1.76 and wasn't aware that Bio.Alphabet is removed in 1.78. Currently, I can only recommend to roll back to 1.76, but I will think of a solution for the next release. Thanks for reporting the issue.
------

Hi, thank you for your reply! Just want to update that it works when using biopython==1.76 :)
